### ISSUE TITLE
Week 1 R Labs

### ISSUE THREAD

**Issue by Stevierene82** [prior-knowledge/bayestime#3]
Put together Rmd versions of the three Week 1 labs:

- [x] 01a - CLT
- [x] 01b - coin  flips
- [x] 01c - elevator repairs

**Comment by Stevierene82** [comment]
Found out the fun way - rstan currently does not play nice with r 3.6.0. [Fun](https://discourse.mc-stan.org/t/running-rstan-with-latest-r-3-6-0-fails-with-error-in-compilecode/8632/11). Go back to feather spray (3.5.1)

**Comment by zamorarr** [comment]
hey @Stevierene82 just started looking at the R labs, Looking good so far. Any place I can help? Also what do you think about rendering the Rmarkdown to `github_document` instead of `html_document`? That way they will display natively on github

**Comment by Stevierene82** [comment]
hey @zamorarr - couple false starts, but finally got `github_document` to work. Pretty fancy. I did not know that was a thing!

I think i'm good atm - but I'll definitely want your review of what I put together. I've not yet had a chance to review the Week 2 lab - so maybe see about getting that rolling?

**Comment by zamorarr** [comment]
hey @Stevierene82 are we doing the elevator lab too?

**Comment by Stevierene82** [comment]
Yep! I'm almost done with it!! Hoping to push it tonight / early tomorrow

**Comment by Stevierene82** [comment]
Closing out since we're past week 1
